schema: "src/lib/graphql/**/*.graphqls"
documents: "src/lib/graphql/**/*.graphql"
schemaEntrypoint: "src/lib/graphql-schema"
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
cacheDir: src/__generated__
