schema: "lib/graphql/**/*.graphqls"
documents: "lib/graphql/**/*.graphql"
schemaEntrypoint: "lib/graphql-schema"
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
cacheDir: __generated__
